### ISSUE TITLE
pillow 10.4.0 build fails on x86

### ISSUE THREAD

**Issue by rmartin16** [beeware/mobile-forge#62]
### Describe the bug

The pillow 10.4.0 build fails on x86 hardware (or at least I can only replicate this on x86).
```
ld: building for 'iOS-simulator', but linking in dylib (/usr/local/Cellar/libtiff/4.6.0/lib/libtiff.6.dylib) built for 'macOS'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/Users/runner/work/mobile-forge-test/mobile-forge-test/support/3.12/iOS/Python.xcframework/ios-arm64_x86_64-simulator/bin/x86_64-apple-ios-simulator-clang' failed with exit code 1
```
https://github.com/rmartin16/mobile-forge-test/actions/runs/10969302765/job/30461795505#step:6:1768

### Steps to reproduce

Build pillow 10.4.0 on x86.

### Expected behavior

Pillow builds irrespective of build hardware.

### Environment

- Operating System: Sonoma and GitHub runner macos-13
- Python version: 3.9-3.13-dev
- Software versions:
  - mobile-forge: eb36d2787ede0fafdfc7e1500df8772106c82512

### Logs

[Pillow-10.4.0-cp311-ios_13_0_arm64_iphoneos.log](https://github.com/user-attachments/files/17085800/Pillow-10.4.0-cp311-ios_13_0_arm64_iphoneos.log)
[Pillow-10.4.0-cp311-ios_13_0_arm64_iphonesimulator.log](https://github.com/user-attachments/files/17085801/Pillow-10.4.0-cp311-ios_13_0_arm64_iphonesimulator.log)
[Pillow-10.4.0-cp311-ios_13_0_x86_64_iphonesimulator.log](https://github.com/user-attachments/files/17085802/Pillow-10.4.0-cp311-ios_13_0_x86_64_iphonesimulator.log)

**Comment by freakboy3742** [comment]
I'm almost certain this is the result of having homebrew somewhere on the path. If homebrew versions of libraries are present, they will get linked into a binary, causing the problem you've shown here.

Mobile forge *should* be stripping  homebrew out of the path; but I might have the invocation wrong for x86 machines.

It's also possible it's not homebrew, but a similar macOS build of a library that Pillow is linking. It's the same problem with a different manifestation.
